In [2]:
import sys
import os

# Go up one level and then into src
src_path = os.path.abspath(os.path.join("..", "src"))
print("Adding to sys.path:", src_path)
sys.path.insert(0, src_path)

import numpy as np
from utils.activations import sigmoid, relu, tanh

activation_funcs = {
    "sigmoid": sigmoid,
    "relu": relu,
    "tanh": tanh
}


Adding to sys.path: /home/pushkar/ActionAI_2/NN_with_backprop/src


In [3]:
layers = []
layers.append(np.zeros(3))
layers.append(np.zeros(2))
layers.append(np.zeros(2))
layers.append(np.zeros(1))

In [4]:
a_f = ["sigmoid", "sigmoid", "sigmoid"]

In [5]:
layers

[array([0., 0., 0.]), array([0., 0.]), array([0., 0.]), array([0.])]

In [6]:
from utils.parameters_init import xavier_init

shape = [(layers[i+1].shape[0], layers[i].shape[0]) for i in range(len(layers)-1)]
weights = [xavier_init(i) for i in shape]
biases = [xavier_init((i[0],)) for i in shape]

In [7]:
shape

[(2, 3), (2, 2), (1, 2)]

In [8]:
weights

[array([[-0.39342589, -0.83212088, -0.86823405],
        [ 0.01744419, -0.33931541, -1.0614814 ]]),
 array([[-0.57651914,  0.79572207],
        [-0.19154693,  0.77534064]]),
 array([[-0.49843523,  0.38230388]])]

In [9]:
biases

[array([ 0.53075375, -0.6326686 ]),
 array([-0.43189567, -0.09908905]),
 array([-0.95434293])]

In [18]:
for i, j in zip(weights, biases):
    print((i.shape, j.shape))

((2, 3), (2,))
((2, 2), (2,))
((1, 2), (1,))


In [23]:
np.array([1, 2]).shape

(2,)

In [44]:
for i in range(len(layers)-1):
    layers[i+1] = weights[i] @ layers[i] + biases[i]
    ac_func = activation_funcs[a_f[i]]
    layers[i+1] = ac_func(layers[i+1])

In [45]:
layers

[array([0., 0., 0.]),
 array([0.37761267, 0.33082915]),
 array([0.3713217 , 0.69279308]),
 array([0.05418484])]

In [43]:
ac_func = activation_funcs[a_f[1]]
ac_func

<function utils.activations.sigmoid(x)>

In [39]:
list(activation_funcs.values())[0]

<function utils.activations.sigmoid(x)>

In [23]:
biases[1]

array([-0.26006705,  0.9547276 ])

In [22]:
sigmoid(biases[1])

array([0.43534722, 0.72206494])

In [29]:
a= 1 / (1 + np.exp( - (np.array([5.97529062]))))

In [33]:
a == 0.997465675536554

array([ True])

In [25]:
- np.array([7, 8])

array([-7, -8])

In [25]:
import math
1 / (1 + math.exp(-0.954776))

0.7220746551277553